### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by aseques** [xdarklight/keystate-plasmoid#1]
Hi, after looking through internet, I found out that most of the keystate widgets are either for gnome (indicator-keylock) or mostly abandoned plasma-widget-kbstate, and not usable on plasma5.
I would like to test your development and I have no idea on installing a plasmoid that's not in kde-look.org

Regards

**Comment by xdarklight** [comment]
Hi,

I must warn you: the configuration dialog is currently not implemented for the Plasma5 version (but I plan to re-add that in the future).

Installing plasma-packages is quite easy:
1. Check out the git repo
2. plasmapkg2 --install /path/to/checkout/of/keystate-plasmoid/

**Comment by aseques** [comment]
Just installed it and it seems to start properly (I can attach it to the plasma panel), but there is no highlight   doesn't matter the keys I press.
I don't see any logging, is there anywhere I could have a look?

**Comment by xdarklight** [comment]
Indeed, this is not working for me as well.

I'm hoping to have time for taking a look at the plasmoid this weekend (then I'll also tackle the config dialog).
But for the moment there's not much you can do - sorry.

**Comment by aseques** [comment]
No problem, when it's done it's done, thanks for your effort.

**Comment by xdarklight** [comment]
Can you please give it another go?
I pushed a lot of updates today and I'd like to know if it's working fine now for you (as it does for me).
And as a bonus I also added a CMakeLists.txt which should have all the information that one needs for installing / updating.

PS: I'm on Arch Linux and running KDE 5.10.0 with Plasma 5.3.0 (that's what Arch Linux' official repositories provide).

**Comment by aseques** [comment]
Just tried it, it's working fine now, I only had to readd the widget or it would be the old one.

Thanks a lot
![kyestate](https://cloud.githubusercontent.com/assets/555542/7701470/b8deaa7a-fe27-11e4-94a3-a0e86fd0b176.png)
