### ISSUE TITLE
Not detecting changes on num lock

### ISSUE THREAD

**Issue by aseques** [xdarklight/keystate-plasmoid#2]
I am on current master (c396e9354c722ae5e4198bfc790b27730eac6691) the indicator works fine for caps lock and for shift (appears and disappears when needed), but for the bloq num it stays all the time in green, I can change the color or enable/disable the indicator, but when on it will remain static all the time.

**Comment by xdarklight** [comment]
I just checked that and it works fine for me.

Could you please have a look at what `plasmaengineexplorer` (from plasma-sdk) says?
Here's how it looks for me: http://abload.de/img/plasmaengineexplorer-frylm.png
Whenever you press "num lock" on your keyboard then "Locked" and "Pressed" should change (both at the same time - and they should always show the same value).

**Comment by aseques** [comment]
Unfortunately, after installing plasmate (ubuntu's name for the package) and getting plasmaengineexplorer installed, it doesn't properly work, it just doesn't show me any of the engines to choose, so I am a bit of stuck here for another bug. I'll try to get some more info there.

**Comment by aseques** [comment]
After paying attention to this, I guess that the issue is related to using either remmina (for connection to windows rdesktop) or vmware-view (for connections via pcoip).
After I log into one of those the indicator for the num lock doesn't change anymore, strangely enough, both caps lock and shift are displayed normally.
Let's see if I can get plasma 5.3 installed on my system and follow from there.

**Comment by xdarklight** [comment]
I just found that kguiaddons provides a "kmodifierkeyinfotest":
http://quickgit.kde.org/?p=kguiaddons.git&a=tree&h=ad49e73ae649f4902bd57812fee5a6ac8763bf3a&hb=a3fc7a8e08746e0ae2472a73d6a45e24f41f3416&f=tests

I haven't tried it yet, but this is what the keystate plasma-dataengine (and thus my plasmoid) uses internally.
It would be interesting to see what it outputs for you when you have one of the "suspicious" applications open.
(just for reference: it always shows the same values as my plasmoid)

**Comment by xdarklight** [comment]
Were you able to test this with kmodifierkeyinfotest yet, @aseques?

**Comment by aseques** [comment]
Unfortunately not, the program is not packed for ubuntu and not that easy
to compoile for me.
In any case I isolated the issue and is only related to vmware, so it won't
affect most of the people even me all the time.
So for me the current version is fine
El dia 20/06/2015 2:39 a. m., "Martin Blumenstingl" <
notifications@github.com> va escriure:

**Comment by xdarklight** [comment]
Okay - feel free to reopen this if there's another way to trigger it!
