### ISSUE TITLE
Cannot use widget in 5.3.2

### ISSUE THREAD

**Issue by aseques** [xdarklight/keystate-plasmoid#4]
I have had the plugin installed for some months now, without issues, recently I updated to current 5.3.2, and the widget stopped working.
My plasma packages are from kubuntu backports and versioned like this "4:5.3.2-0ubuntu1~ubuntu15.04~ppa1"

The message that appears on screen when clicking on the widget is the following:
Error loading QML file: file:///home/user/.local/share/plasma/plasmoids/eu.blumenstingl.martin.keystateplasmoid/contents/ui/main.qml:4:1: Script plasmapackage:/code/logic.js unavailable
plasmapackage:/code/logic.js: Network error

**Comment by xdarklight** [comment]
Can you please try 23df9ac894fc08872b2f3b45ef021d8fdf066146 or later?
I ran into the same problem when Arch Linux updated to KF 5.12

**Comment by aseques** [comment]
It seems that plasmapkg -u didn't do it's job well enough. Prior opening this bug I had already done a git pull + plasmapkg -u, but the main.qml file from .local wasn't updated.
Now I removed the folder manually and did a plasmapkg -i, unfortunately it still doesn't show the keystate plasmoid on the list, (any tips on refreshing this?)

**Comment by xdarklight** [comment]
Are you running plasmapkg -u from &lt;git root&gt; or from &lt;git root&gt;/package/?
The latter one is correct (I had to create a subdirectory to make the life of package managers easier in case this plasmoid makes into a distro's repo at some point).

**Comment by aseques** [comment]
I was using the later, strangely enough, until I rebooted the computer and tried a couple of times it didn't appear on the plasmoid list.

```
plasmapkg -u package/
Successfully removed eu.blumenstingl.martin.keystateplasmoid
Successfully installed /home/jjuvanteny/src/keystate-plasmoid/package
```

It seems to me that it's failing because of issues on the plasmapkg tool, but I really can't see a logic behind it.
It's working now, thanks a lot!

**Comment by xdarklight** [comment]
Glad that it works now - and thanks for giving feedback!
