### ISSUE TITLE
Visible indicator if disabled

### ISSUE THREAD

**Issue by dkadioglu** [xdarklight/keystate-plasmoid#5]
Hi,

first of all, thanks for porting this to KF5! It's a useful and necessary plasmoid.
But there is one feature I miss: It would be better if the indicators are visible even if the respective key is disabled/not pressed. In that case there is an empty space now, which is irritating. Could you change the behaviour accordingly? For example like this one:
http://kde-apps.org/content/show.php/LockKeysState+QML?content=152082

Thanks in advance!

**Comment by xdarklight** [comment]
Hi,

sorry for the late reply.
Adding that feature shouldn't be hard - I can look at it in the next few weeks.

**Comment by dkadioglu** [comment]
Hi,

thank you very much for looking into this. I would like to ask if you've already started with it? Is there some rough ETA?

Thanks again.

**Comment by xdarklight** [comment]
Today is the day :)
I had to make a few more changes.

Let me know if it works for you!

**Comment by dkadioglu** [comment]
Thank you very much! It works very well and looks better than showing an empty space.
